# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-13 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lightning', models.BooleanField(default=True, verbose_name='Available')),
                ('current', models.BooleanField(default=False, verbose_name='Current')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Human')),
            ],
            options={
                'verbose_name': 'Human',
                'verbose_name_plural': 'Humans',
            },
        ),
        migrations.CreateModel(
            name='Talks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('cicle', models.IntegerField(verbose_name='Cicle')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Human')),
            ],
            options={
                'verbose_name': 'Talk',
                'verbose_name_plural': 'Talks',
            },
        ),
    ]
