# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-27 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_talks_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='talks',
            name='topic',
            field=models.CharField(choices=[('team_culture', 'Team Culture'), ('product_management', 'Product Mgmt'), ('marketing', 'Marketing'), ('tech', 'Technology'), ('design', 'Design')], default='card', max_length=100),
        ),
    ]
