# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-27 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181226_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/avatars/'),
        ),
    ]
